package com.qinhailin.common.model;

import java.util.Date;

import com.qinhailin.common.model.base.BaseSysLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLog extends BaseSysLog<SysLog> {
	
	public SysLog(){
		
	}
	
	public SysLog(String id,String url,Date createTime,String data,String ip){
		this.setId(id);
		this.setUrl(url);
		this.setCreateTime(createTime);
		this.setData(data);
		this.setIp(ip);
	}
}
