package com.qinhailin.common.model;

import com.qinhailin.common.model.base.BaseSysOrg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOrg extends BaseSysOrg<SysOrg> {

}
