package com.qinhailin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysRole<M extends BaseSysRole<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setDescript(java.lang.String descript) {
		set("descript", descript);
		return (M)this;
	}
	
	public java.lang.String getDescript() {
		return getStr("descript");
	}

	public M setIsStop(java.lang.Integer isStop) {
		set("is_stop", isStop);
		return (M)this;
	}
	
	public java.lang.Integer getIsStop() {
		return getInt("is_stop");
	}

	public M setOrgid(java.lang.String orgid) {
		set("orgid", orgid);
		return (M)this;
	}
	
	public java.lang.String getOrgid() {
		return getStr("orgid");
	}

	public M setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	public java.lang.String getParentId() {
		return getStr("parent_id");
	}

	public M setRoleCode(java.lang.String roleCode) {
		set("role_code", roleCode);
		return (M)this;
	}
	
	public java.lang.String getRoleCode() {
		return getStr("role_code");
	}

	public M setRoleName(java.lang.String roleName) {
		set("role_name", roleName);
		return (M)this;
	}
	
	public java.lang.String getRoleName() {
		return getStr("role_name");
	}

	public M setUserCode(java.lang.String userCode) {
		set("user_code", userCode);
		return (M)this;
	}
	
	public java.lang.String getUserCode() {
		return getStr("user_code");
	}

	public M setVisitView(java.lang.String visitView) {
		set("visit_view", visitView);
		return (M)this;
	}
	
	public java.lang.String getVisitView() {
		return getStr("visit_view");
	}

}
