package com.qinhailin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysRoleFunction<M extends BaseSysRoleFunction<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setFunctionId(java.lang.String functionId) {
		set("function_id", functionId);
		return (M)this;
	}
	
	public java.lang.String getFunctionId() {
		return getStr("function_id");
	}

	public M setRoleCode(java.lang.String roleCode) {
		set("role_code", roleCode);
		return (M)this;
	}
	
	public java.lang.String getRoleCode() {
		return getStr("role_code");
	}

}
