package com.qinhailin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setUserCode(java.lang.String userCode) {
		set("user_code", userCode);
		return (M)this;
	}
	
	public java.lang.String getUserCode() {
		return getStr("user_code");
	}

	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public M setPasswd(java.lang.String passwd) {
		set("passwd", passwd);
		return (M)this;
	}
	
	public java.lang.String getPasswd() {
		return getStr("passwd");
	}

	public M setOrgId(java.lang.String orgId) {
		set("org_id", orgId);
		return (M)this;
	}
	
	public java.lang.String getOrgId() {
		return getStr("org_id");
	}

	public M setPost(java.lang.String post) {
		set("post", post);
		return (M)this;
	}
	
	public java.lang.String getPost() {
		return getStr("post");
	}

	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setAllowLogin(java.lang.Integer allowLogin) {
		set("allow_login", allowLogin);
		return (M)this;
	}
	
	public java.lang.Integer getAllowLogin() {
		return getInt("allow_login");
	}

	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}

	public M setAllowLoginTime(java.util.Date allowLoginTime) {
		set("allow_login_time", allowLoginTime);
		return (M)this;
	}
	
	public java.util.Date getAllowLoginTime() {
		return get("allow_login_time");
	}

	public M setFailureNumber(java.lang.Integer failureNumber) {
		set("failure_number", failureNumber);
		return (M)this;
	}
	
	public java.lang.Integer getFailureNumber() {
		return getInt("failure_number");
	}

}
